newscoop_tageswochemobile_plugin:
    resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /api2

newscoop_tageswochemobile_plugin:
    resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/ArticlesController.php"
    type:     annotation
    prefix:   /api2/articles
