services:
    newscoop_tageswochemobile_plugin.lifecyclesubscriber:
        class: Newscoop\TagesWocheMobilePluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

    newscoop_tageswochemobile_plugin.configure_menu_listener:
        class: Newscoop\TagesWocheMobilePluginBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments:
            - @translator

    newscoop_tageswochemobile_plugin.api_helper:
        class: Newscoop\TagesWocheMobilePluginBundle\Services\ApiHelper
        arguments:
            - @em
            - @service_container

    newscoop_tageswochemobile_plugin.render_slideshow_helper:
        class: Newscoop\TagesWocheMobilePluginBundle\Services\RenderSlideshowHelper
        arguments:
            - @em
            - @service_container

    newscoop_tageswochemobile_plugin.cache_helper:
        class: Newscoop\TagesWocheMobilePluginBundle\Services\CacehHelper

    newscoop_tageswochemobile_plugin.debate:
        class: Newscoop\TagesWocheMobilePluginBundle\Debate\DebateService
        arguments:
            - @em
